# Generated by Django 2.2.12 on 2020-09-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='propic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
