# Generated by Django 2.2.12 on 2020-10-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Libri', 'Libri'), ('Strumenti', 'Strumenti'), ('Poster', 'Poster')], max_length=30, null=True),
        ),
    ]
