# Generated by Django 2.2.12 on 2020-10-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20201001_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In elaborazione', 'In elaborazione'), ('Spedito', 'Spedito'), ('Consegnato', 'Consegnato')], default='In elaborazione', max_length=200, null=True),
        ),
    ]
